const $ = id => document.getElementById(id);
let statsTimer;
let statsLoading = false;
function formatBytes(value = 0) { if (!value) return "0 o"; const units = ["o", "Ko", "Mo", "Go"]; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** index).toLocaleString("fr-FR", { maximumFractionDigits: 1 })} ${units[index]}`; }
function scheduleStats() { clearTimeout(statsTimer); statsTimer = setTimeout(loadStats, 2000); }
function loadStats() { if (statsLoading) return; statsLoading = true; chrome.runtime.sendMessage({ type: "stats" }, result => { statsLoading = false; if (chrome.runtime.lastError) { $("statsStatus").textContent = "Connexion au service interrompue"; scheduleStats(); return; } if (!result?.ok) { $("statsStatus").textContent = result?.error || "Statistiques indisponibles"; $("reconnect").hidden = !result?.authInvalid; scheduleStats(); return; } $("reconnect").hidden = true; const data = result.data; $("welcomeLabel").textContent = `${data.client.name}, votre navigation est optimisée.`; $("bytesSaved").textContent = formatBytes(data.bytesSaved); $("requests").textContent = Number(data.requests).toLocaleString("fr-FR"); $("imagesCompressed").textContent = Number(data.imagesCompressed).toLocaleString("fr-FR"); $("statsStatus").textContent = `Actualisé à ${new Date().toLocaleTimeString("fr-FR")}`; scheduleStats(); }); }
function showConnected(session = {}) { $("loginView").hidden = true; $("connectedView").hidden = false; $("statusDot").classList.add("on"); $("directList").value = (session.directList || []).join(", "); clearTimeout(statsTimer); loadStats(); }
function showLogin(session = {}) { clearTimeout(statsTimer); statsLoading = false; $("loginView").hidden = false; $("connectedView").hidden = true; $("statusDot").classList.remove("on"); $("username").value = session.username || ""; }
chrome.runtime.sendMessage({ type: "status" }, session => session && session.connected && !session.needsReconnect ? showConnected(session) : showLogin(session));
$("loginForm").addEventListener("submit", event => { event.preventDefault(); const button = event.submitter; button.disabled = true; $("error").textContent = ""; chrome.runtime.sendMessage({ type: "connect", username: $("username").value, password: $("password").value }, result => { button.disabled = false; if (!result || !result.ok) { $("error").textContent = result?.error || "Connexion impossible"; return; } chrome.runtime.sendMessage({ type: "status" }, session => showConnected(session || {})); $("password").value = ""; }); });
$("disconnect").addEventListener("click", () => chrome.runtime.sendMessage({ type: "disconnect" }, () => showLogin()));
$("reconnect").addEventListener("click", () => chrome.runtime.sendMessage({ type: "disconnect" }, () => showLogin()));
$("saveDirectList").addEventListener("click", () => chrome.runtime.sendMessage({ type: "updateDirectList", directList: $("directList").value }, result => { $("statsStatus").textContent = result?.ok ? "Liste directe enregistrée" : (result?.error || "Enregistrement impossible"); }));
