const states = new Map();
function createState() { return { requests: 0, imagesCompressed: 0, bytesOriginal: 0, bytesServed: 0, trackersStripped: 0, hostsSeen: new Set(), unsupportedEncodings: new Map(), byHost: new Map() }; }
function requireClientId(clientId) { const id = String(clientId || "").trim(); if (!id) throw new Error("Client ID required for statistics"); return id; }
function stateFor(clientId) { const id = requireClientId(clientId); if (!states.has(id)) states.set(id, createState()); return states.get(id); }
function hostEntry(state, host) { if (!state.byHost.has(host)) state.byHost.set(host, { requests: 0, imagesCompressed: 0, bytesOriginal: 0, bytesServed: 0, trackersStripped: 0, unsupportedEncodings: {} }); return state.byHost.get(host); }
function recordUnsupportedEncoding(encoding, host, clientId) { const state = stateFor(clientId), key = encoding || "(vide)"; state.unsupportedEncodings.set(key, (state.unsupportedEncodings.get(key) || 0) + 1); if (host) { const item = hostEntry(state, host); item.unsupportedEncodings[key] = (item.unsupportedEncodings[key] || 0) + 1; } }
function recordRequest(host, clientId) { const state = stateFor(clientId); state.requests += 1; if (host) { state.hostsSeen.add(host); hostEntry(state, host).requests += 1; } }
function recordImageCompression(originalBytes, servedBytes, host, clientId) { const state = stateFor(clientId); state.imagesCompressed += 1; state.bytesOriginal += originalBytes; state.bytesServed += servedBytes; if (host) { const item = hostEntry(state, host); item.imagesCompressed += 1; item.bytesOriginal += originalBytes; item.bytesServed += servedBytes; } }
function recordTrackersStripped(count, host, clientId) { const state = stateFor(clientId); state.trackersStripped += count; if (host) hostEntry(state, host).trackersStripped += count; }
function ratioAndSaved(original, served) { return { bytesSaved: original - served, compressionRatio: Number((original > 0 ? original / Math.max(served, 1) : 0).toFixed(2)) }; }
function getStats(clientId) { const state = stateFor(clientId), byHost = {}; for (const [host, item] of state.byHost) byHost[host] = { ...item, ...ratioAndSaved(item.bytesOriginal, item.bytesServed) }; return { requests: state.requests, imagesCompressed: state.imagesCompressed, trackersStripped: state.trackersStripped, bytesOriginal: state.bytesOriginal, bytesServed: state.bytesServed, ...ratioAndSaved(state.bytesOriginal, state.bytesServed), hostsSeen: [...state.hostsSeen], unsupportedEncodings: Object.fromEntries(state.unsupportedEncodings), byHost }; }
function resetStats(clientId) { states.set(requireClientId(clientId), createState()); }
module.exports = { recordRequest, recordImageCompression, recordTrackersStripped, recordUnsupportedEncoding, getStats, resetStats };
